5. Обратная сторона реальности
htmlacademy-react/1486707-six-cities-6 pull request #6
Opened 2021-02-17 16:11 UTC by vladn255

Не всё сделал, не понял смысл пункта 8: "Используя компонент Link из пакета react-router-dom и возможности пропса history свяжите страницы приложения. Например, клик по заголовку карточки предложения должен переводить пользователя на страницу «Room» с подробным описанием предложения по аренде." В чём в данном случае будет смысл пропса history? Для чего он здесь нужен и какие функции должен выполнять?
В остальном, вроде, всё сделал, если только не просмотрел что-нибудь.

2021-02-18 08:52 UTC, Shv-sergey70 requested changes

2021-02-18 08:52 UTC, Shv-sergey70 commented on src/components/favorites/favorites.jsx
> +import PlacesListComponent from "../places-list/places-list.jsx";
окончание `Component` излишне

2021-02-18 08:52 UTC, Shv-sergey70 commented on src/components/place-card/place-card.jsx
> +  const mouseOverHandler = props.mouseOverHandler;
Нужные 2 пропса можно деструктурировать сразу в параметре

2021-02-18 08:52 UTC, Shv-sergey70 commented on src/components/place-card/place-card.jsx
> +          <Link to="/offer/:id">{title}</Link>
Чтобы переходы корректно работали, нужно прописывать реальный id, вместо заглушки `:id`. То есть так:
```
<Link to={`/offer/${id}`}>{title}</Link>
```

2021-02-18 08:52 UTC, Shv-sergey70 commented on src/components/place-card/place-card.jsx
> +  mouseOverHandler: mouseOverHandlerType
Это описание пропса же используется в одном месте, нет смысла его выносить в отдельный файл

2021-02-18 08:52 UTC, Shv-sergey70 commented on src/components/places-list/places-list.jsx
> +    activeCardId = articleId;
Так делать нельзя. Мы используем только `setActiveCard` как единственный способ изменить стейт

2021-02-18 08:52 UTC, Shv-sergey70 commented on src/components/review-form/review-form.jsx
> +          </label>
Это можно сделать отдельным компонентом, чтобы 5 раз не дублировать код

2021-02-18 08:52 UTC, Shv-sergey70 commented on src/const.js
> +const Routes = {
Это перечисление, поэтому оно должно быть в единственном числе

2021-02-18 08:52 UTC, Shv-sergey70 commented on src/components/app/app.jsx
> +          <OfferScreenComponent placeCards={placeCards}/>
Тут имеет смысл передавать 2 пропса, вместо одного. 1 - подробное описание для карточки, 2 - массив похожих карточек.
Причем нужно определять id выбранной карточки из url, и находить в массиве нужную карточку, затем отправлять ее 1 пропсом и отрисовывать релевантную информацию

2021-02-18 08:54 UTC, Shv-sergey70 commented
__Не всё сделал, не понял смысл пункта 8: "Используя компонент Link из пакета react-router-dom и возможности пропса history свяжите страницы приложения. Например, клик по заголовку карточки предложения должен переводить пользователя на страницу «Room» с подробным описанием предложения по аренде." В чём в данном случае будет смысл пропса history? Для чего он здесь нужен и какие функции должен выполнять?__

Хороший вопрос. Нет смысла пока использовать `history`. В основном он используется, если нужно по каким-то условиям или в каком-то обработчике сделать переход пользователя на другую страницу. Сейчас мы можем пользоваться `Link` компонентом и этого достаточно

2021-02-18 17:15 UTC, vladn255 commented
Поправил, но не совсем допёр как поправить по замечанию "Причем нужно определять id выбранной карточки из url, и находить в массиве нужную карточку, затем отправлять ее 1 пропсом и отрисовывать релевантную информацию". Сделал только, чтобы рендерилась нужная карточка из списка, но отправляю все карточки первым пропсом. Как тут следовало сделать правильно?

2021-02-19 12:30 UTC, Shv-sergey70 commented
__Поправил, но не совсем допёр как поправить по замечанию "Причем нужно определять id выбранной карточки из url, и находить в массиве нужную карточку, затем отправлять ее 1 пропсом и отрисовывать релевантную информацию". Сделал только, чтобы рендерилась нужная карточка из списка, но отправляю все карточки первым пропсом. Как тут следовало сделать правильно?__

```
        <Route exact path={RoutePath.OFFER} render={({match}) => {
          const placeCard = placeCards.find(({id}) => id === Number(match.params.id));

          return <OfferScreen
            placeCard={placeCard}
            placeCardsNearby={placeCardsNearby}/>;
        }}/>
```

2021-02-19 12:30 UTC, merged