Module4 task2
htmlacademy-react/1486707-six-cities-6 pull request #9
Opened 2021-03-01 06:51 UTC by vladn255

Вроде, ничего не забыл. Единственное сомнение вызывает формат отображения даты для отзывов - воспользовался стандартным объектом Date, чтобы не тянуть лишнюю библиотеку в проект (date.js). Это нормальный вариант, или надо переделать этот момент?

2021-03-01 13:36 UTC, Shv-sergey70 requested changes
Даты нужно отформатировать в нужном формате

2021-03-01 13:36 UTC, Shv-sergey70 commented on src/components/app/app.jsx
> +  reviewList: reviewListType
`isRequired`?

2021-03-01 13:36 UTC, Shv-sergey70 commented on src/utils.js
> +};
Используй короткий синтаксис стрелочных функций

2021-03-01 13:36 UTC, Shv-sergey70 commented on src/components/review-item/review-item.jsx
> +        <time className="reviews__time" dateTime={dateParced}>{dateParced.toDateString()}</time>
В целом ты можешь использовать объект `Date`, но формат даты должен в точности совпадать с тем что в макете, и используя `Date` это будет сделать немного сложнее

2021-03-01 13:36 UTC, Shv-sergey70 commented on src/components/map/map.jsx
> +    points.forEach((point) => {
`point` определенно стоит деструктурировать

2021-03-01 14:49 UTC, vladn255 commented on src/components/app/app.jsx
> +  reviewList: reviewListType
Я применил isRequired к типам этих данных в types.js. Это же значит, что этот параметр будет применяться, когда ссылаешься на тип данных в app, нет?

2021-03-02 13:46 UTC, Shv-sergey70 commented on src/components/app/app.jsx
> +  reviewList: reviewListType
Да, `isRequired` будет проставлен. Тогда аналогично нужно сделать для `reviewItemType`

2021-03-02 13:48 UTC, Shv-sergey70 commented on src/components/review-item/review-item.jsx
> +        <time className="reviews__time" dateTime={newDate}>{dateParsed}</time>
Если посмотреть пример исходной разметки, то `dateTime` там в другом формате:
![image](https://user-images.githubusercontent.com/35741647/109657969-2232a080-7b77-11eb-9b69-edcd929eff70.png)

2021-03-02 13:49 UTC, merged